version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
    volumes:
      - ./data:/var/lib/mysql

  api:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_PWD=root_password
    depends_on:
      - mysql
